### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [aneksteind/Core-Compiler#1]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by oinoom** [comment]
I bumped the version after double checking the formatting of the docks, so we will see what happens

**Comment by oinoom** [comment]
documentation works now

**Comment by expipiplus1** [comment]
Thanks!
